config/routes.rb
Friends::Application.routes.draw do
  
  patch 'users/:user_id/meetups/:id/accept' => 'meetups#accept', as: :accept_meetup #accept meet up

  resources :users do
    resources :meetups
  end

  # Profile
  get 'profile' => 'profile#index' # list all profiles 
  get 'profile/edit_current' => 'profile#edit_current', as: :edit_current # form to edit profile
  get 'profile/search' => 'profile#search', as: :search_profiles
  get 'profile/:id' => 'profile#show', as: :show_profile # show one profile
  get 'profile/:id/edit' => 'profile#edit', as: :edit_profile # form to edit profile
  put 'profile/:id' => 'profile#update' # update a profile
  patch 'profile/:id' => 'profile#update' # update a profile  


  scope :api do
    resources :profiles, except: [ :new, :edit ], default: {format: :json}

    get 'profiles/:profile_id/subjects/:subject_id' => 'subjects#show'
  end

  # Sign in/out
  get    'login' => 'session#new', as: :login
  post   'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'
  
  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'
  
  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'
  
  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'
  
  root 'profile#show_current'
end

app/models/meetup.rb
class Meetup 
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  belongs_to :primary, class_name: "User", inverse_of: :meetups_as_primary
  belongs_to :friend, class_name: "User", inverse_of: :meetups_as_friend

  field :request_person, type: Boolean
  field :meetup_at, type: Time
  field :place, type: String

  
  field :is_coffee, type: Boolean
  field :is_beer, type: Boolean
  field :acceptStatus, type: Boolean

  field :expires_at, type: Time
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  # List all persons (show table of persons in HTML)
  def index
    present = Time.now
    year = present.year
    month = present.month
    day = present.day
    @today = Date.new(year, month, day)
  	@current_user=current_user
    @meetupsP = current_user.meetups_as_primary
    @meetupsF = current_user.meetups_as_friend
    @meetupDateComing=[]
    @event=[]

    @calendar=[]
    @calendarD=[]
    #offset=@today.wday-1
    fday=@today.beginning_of_week
    for i in 0..13
      @calendar[i]=fday+i
    end

    @calendarD=@calendar.map { |n| n.day }

    for i in 0..13
      @event[i]=[]
    end

    @meetupsF.each do |m| 
          meetup_year=m.meetup_at.year
          meetup_month=m.meetup_at.month
          meetup_day=m.meetup_at.day
          meetup_date= Date.new(meetup_year, meetup_month, meetup_day)
          meetup_time=formatTime(m.meetup_at.hour, m.meetup_at.min)
          if meetup_date > fday
            if meetup_date < fday + 14
              if m.acceptStatus 
                status="Agreed"
              else
                if (m.primary==current_user)
                  status="Waiting"
                else status="Respond"
                end
              end
              
              @event[meetup_date-fday] = [meetup_time,m, status]
            else
              # here means (meetup_date > fday && meetup_date > fday + 14)
            end
          else
            # here means (meetup_date < fday)
          end
    end

    @meetupsP.each do |m| 
          meetup_year=m.meetup_at.year
          meetup_month=m.meetup_at.month
          meetup_day=m.meetup_at.day
          meetup_date= Date.new(meetup_year, meetup_month, meetup_day)
          meetup_time=formatTime(m.meetup_at.hour, m.meetup_at.min)
          if meetup_date > fday
            if meetup_date < fday + 14
                if m.acceptStatus 
                status="Agreed"
              else
                if (m.primary==current_user)
                  status="Waiting"
                else status="Respond"
                end
              end
              
              @event[meetup_date-fday] = [meetup_time,m, status]
            else
              # here means (meetup_date > fday && meetup_date > fday + 14)
            end
          else
            # here means (meetup_date < fday)
          end
    end

    # TODO fill up all the gaps

   
  end
  
  
  # Show detail for a person with ID = params[:id] (in HTML)
  def show
    @meetup = Meetup.find_by(id: params[:id])
  end
  
  # Form for adding a new meetup (in HTML)
  def new
    @meetup = Meetup.new
    @user = User.find_by(id: params[:user_id])
  end
  
  # POST to this to create a new person, then redirect to show
  def create
    meetup = Meetup.new(meetup_params)
    meetup.friend = User.find_by(id: params[:user_id])
    meetup.primary = current_user
    meetup.acceptStatus=false
    meetup.meetup_at+=8.hour
    meetup.save
    
    redirect_to user_meetup_url(current_user, meetup)
  end
  
  # Form for updating a meetup with ID = params[:id] (in HTML)
  def edit
    @user = current_user
    @meetup = Meetup.find_by(id: params[:id])
    if (@meetup.primary != @user) then
      @meetup.friend = @meetup.primary
      @meetup.primary = @user
    end
    @meetup.save
  end
  
  # PUT or PATCH to this to update person with ID = params[:id]
  # then redirect to show
  
  def accept
    @meetup = Meetup.find_by(id: params[:id])
    @meetup.acceptStatus = true
    @meetup.save
    
    redirect_to user_meetup_url(current_user, @meetup)
  end

  def update
    @meetup = Meetup.find_by(id: params[:id])
    @meetup.update_attributes(meetup_params)
    @meetup.meetup_at+=8*60*60
    @meetup.save
    
    redirect_to user_meetup_url(current_user, @meetup)
  end
  
  # Destroy the person with ID = params[:id]
  # then redirect to index to list remaining persons
  def destroy
    @meetup = Meetup.find_by(id: params[:id])
    @meetup.destroy
    
    redirect_to user_meetups_url(current_user)
  end
  
  private

  def parse_meetup_at(params)
    year = params[:meetup].delete(:"meetup_at(1i)")
    month = params[:meetup].delete(:"meetup_at(2i)")
    day = params[:meetup].delete(:"meetup_at(3i)")
    hour = params[:meetup].delete(:"meetup_at(4i)")
    minute = params[:meetup].delete(:"meetup_at(5i)")

    Time.new(year, month, day, hour, minute)
  end
  
  def meetup_params
    params.require(:meetup).permit(
      :place, :is_coffee, :is_beer
    ).merge({meetup_at: parse_meetup_at(params)} )

    # params.merge({meetup: {meetup_at: parse_meetup_at(params)} } )
  end

  def formatTime(h,m)
    hString = h.to_s
    mString = m.to_s
    if h<10
      hString="0"+h.to_s
    end

    if m<10
      mString="0"+m.to_s
    end

    "@"+hString+":"+mString
  end

end

app/views/meetups/_form.html.slim
p Meet Up Request by
= form_for [@user, @meetup] do |f|
  p
    = f.label :meetup_at
    br
    = f.datetime_select :meetup_at
  p
    = f.label :Place
    br
    = f.text_field :place
  p
    = f.label :Coffee
    br
    = f.check_box :is_coffee
  p
    = f.label :Beer
    br
    = f.check_box :is_beer
  p
    = f.submit

app/views/meetups/edit.html.slim
h1 Edit Meetup

== render partial: 'form'

app/views/meetups/index.html.slim
h1 Meetups

.row
  .col-lg-8.col-lg-offset-2
    table#meetups-table.table.table-bordered.table-striped
      caption Schedules! Today #{@today} 
      thead
        tr
          th Mon
          th Tue
          th Wed
          th Thu
          th Fri
          th Sat
          th Sun
      tbody
        tr
        - for i in 0..6
          td 
            span  #{@calendarD[i]} 
            - if @event[i]!=[]
              - case @event[i][2]
              - when "Agreed"
                - classLabel="label label-success"
              - when "Respond"
                - classLabel="label label-warning"
              - else
                - classLabel="label label-default"
              = link_to @event[i][0], user_meetup_url(@current_user, @event[i][1]), class:classLabel
              span #{@event[i][2]}
        end

        tr
         - for i in 7..13
          td 
            span  #{@calendarD[i]} 
            - if @event[i]!=[]
              - case @event[i][2]
              - when "Agreed"
                - classLabel="label label-success"
              - when "Respond"
                - classLabel="label label-warning"
              - else
                - classLabel="label label-default"
              = link_to @event[i][0], user_meetup_url(@current_user, @event[i][1]), class:classLabel
              span #{@event[i][2]}
        end
      



h1 Primary meetup
table 
  - @meetupsP.each do |p|
    tr
      td style="width: 40%" With #{p.friend.name}
      td style="width: 20%"= link_to "Show", user_meetup_url(@current_user, p)
      td style="width: 20%"= link_to "Edit", edit_user_meetup_url(@current_user,p)
      td = link_to "Delete", user_meetup_url(@current_user,p), method: :delete, confirm: "Are you sure?"
h1 Friend meetup
table 
  - @meetupsF.each do |p|
    tr
      td style="width: 40%" From #{p.primary.name}
      td style="width: 20%"= link_to "Show", user_meetup_url(@current_user, p)
      td style="width: 20%"= link_to "Edit", edit_user_meetup_url(@current_user,p)
      /td = link_to "Delete", user_meetups_url(@current_user,p), method: :delete, confirm: "Are you sure?"

javascript:
  $(function() {
   // $('#meetups-table.table').hide();
   	
    $('#users-table').find('.keyword').on('click', function(e) { 
      e.preventDefault();
      //console.log($(this).html());/
      $(this).addClass('colorOrange');
      //console.log("$(this).attr('data-name'):"+ $(this).attr('data-name'));
      var profile_id = $(this).data("profile-id");
      var subject_id = $(this).data("subject-id");

      $('#details-table').show();
       $.ajax({
        url: "/api/profiles/" + profile_id+ "/subjects/" + subject_id,
        method: "GET",
        dataType: "json",
        
        success: function(data) {
          var thoughtD = $('#thoughts');
          var thoughtLen = data.thoughts.length;
          var questionD = $('#questions');
          var questionLen = data.questions.length;
          
          for (var i = 0; i < thoughtLen; i++) {
            thoughtD.empty();
            thoughtD.append('<li>' + data.thoughts[i]+'</li>');
          }
          for (var i = 0; i < questionLen; i++) {          
            questionD.empty();
            questionD.append('<li>' + data.questions[i]+'</li>');
          }
        }
      });

    });

  
  });

app/views/meetups/new.html.slim
h1 #{current_user.name} adding a new meetup with #{@user.name}

== render partial: 'form'

app/views/meetups/show.html.slim
.row
  .col-lg-6.col-lg-offset
    table#users-table.table.table-bordered.table-striped
      caption Meetup Details
      tbody
        tr
          td
            strong Time
          td = @meetup.meetup_at.strftime('%I:%M%p %a %d %b %Y')
        tr
          td
            strong Place
          td = @meetup.place
        tr
          td
            strong Type
          td #{ @meetup.is_coffee ? "Coffee" : "Beer" }
        tr
          td
            strong Friend
          td #{ @meetup.primary==current_user ? "Invitation To "+@meetup.friend.name : "Invitation From "+@meetup.primary.name }
        tr
          td
            strong Status
          td.status #{ @meetup.acceptStatus ? "Accepted" : "Pending" }


- if (!@meetup.acceptStatus)&&(@meetup.friend==current_user)
  = form_for [current_user, @meetup], url: accept_meetup_path(current_user, @meetup) do |f|
    p
      = f.submit "Accept", id: "accept-button", class: "btn btn-success"
/button#accept-button.btn.btn-success