config/routes.rb
Friends::Application.routes.draw do
  
  patch 'users/:user_id/meetups/:id/accept' => 'meetups#accept', as: :accept_meetup #accept meet up

  resources :users do
    resources :meetups
  end

  # Profile
  get 'profile' => 'profile#index' # list all profiles 
  get 'profile/edit_current' => 'profile#edit_current', as: :edit_current # form to edit profile
  get 'profile/search' => 'profile#search', as: :search_profiles
  get 'profile/:id' => 'profile#show', as: :show_profile # show one profile
  get 'profile/:id/edit' => 'profile#edit', as: :edit_profile # form to edit profile
  put 'profile/:id' => 'profile#update' # update a profile
  patch 'profile/:id' => 'profile#update' # update a profile  


  scope :api do
    resources :profiles, except: [ :new, :edit ], default: {format: :json}

    get 'profiles/:profile_id/subjects/:subject_id' => 'subjects#show'
  end

  # Sign in/out
  get    'login' => 'session#new', as: :login
  post   'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'
  
  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'
  
  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'
  
  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'
  
  root 'profile#show_current'
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  
  def edit
    @user = User.find_by(code: params[:code])
    puts
    puts @user.inspect
    puts
    if @user && @user.expires_at > Time.now
      render :edit
    else
      redirect_to login_url, error: "Sorry, your code has expired. Please try again."
    end
  end
  
  def update
    @user = User.find_by(code: params[:code])
    
    if @user.update_attributes(user_params)
      @user.code = nil
      @user.expires_at = nil
      @user.save
      
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Your password has been updated."
    else
      flash.now[:error] = "Something went wrong. Please check your passwords and try again."
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :password,
      :password_confirmation
    )
  end
end

app/views/password/edit.html.slim
.row
  .col-lg-4.col-lg-offset-4
    h1 Please choose a new password
    .row
      .col-lg-9
        = form_for :user, url: reset_url, method: :put, html: { role: "form" } do |f|
          .form-group
            = f.label :password
            = f.password_field :password, class: "form-control showable-password", placeholder: "Password"
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, class: "form-control showable-password", placeholder: "Type it again"
          .form-group
            => f.submit "Save", class: "btn btn-success"
            button#show-password-button.btn.btn-warning data-state="show" Show Passwords

== render partial: 'layouts/password'