config/routes.rb
Friends::Application.routes.draw do
  
  patch 'users/:user_id/meetups/:id/accept' => 'meetups#accept', as: :accept_meetup #accept meet up

  resources :users do
    resources :meetups
  end

  # Profile
  get 'profile' => 'profile#index' # list all profiles 
  get 'profile/edit_current' => 'profile#edit_current', as: :edit_current # form to edit profile
  get 'profile/search' => 'profile#search', as: :search_profiles
  get 'profile/:id' => 'profile#show', as: :show_profile # show one profile
  get 'profile/:id/edit' => 'profile#edit', as: :edit_profile # form to edit profile
  put 'profile/:id' => 'profile#update' # update a profile
  patch 'profile/:id' => 'profile#update' # update a profile  


  scope :api do
    resources :profiles, except: [ :new, :edit ], default: {format: :json}

    get 'profiles/:profile_id/subjects/:subject_id' => 'subjects#show'
  end

  # Sign in/out
  get    'login' => 'session#new', as: :login
  post   'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout
  get    'logout' => 'session#destroy'
  
  # Registration
  get  'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'
  
  # Password reset
  get   'reset/:code' => 'password#edit', as: :reset
  put   'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'
  
  get 'privacy' => 'site#privacy'
  get 'terms'   => 'site#terms'
  
  root 'profile#show_current'
end

app/views/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top
  .container
    span.navbar-brand.logo Friends 
    	

app/views/layouts/_messages.html.slim
- flash.each do |name, message|
  - if message.is_a?(String)
    - noty_type = (name == :notice ? "success" : "error")
    - timeout = (name == :notice ? 4000 : 30000)
    javascript:
      $(function() {
        noty({
          layout: 'top',
          type: "#{noty_type}",
          text: "#{message}",
          timeout: "#{timeout}"
        });
      });

app/views/layouts/_navigation.html.slim
.navbar.navbar-inverse.navbar-fixed-top
  .container
    button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to_unless_current "Friends", root_url, class: "navbar-brand logo" do
      span.navbar-brand.logo Friends
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        li
          = link_to "Schedule", user_meetups_url(current_user), class: "schedule-link"   
        li
          = link_to "Edit", edit_current_url, class: "edit-link"
        li
          = link_to "Search", search_profiles_url, class: "search-link"
        li
          = link_to "Sign out", logout_url, method: :delete, class: "logout-link"

app/views/layouts/_password.html.slim
javascript:
  $(function() {
  
    $('#show-password-button').on('click', function(e) {
      switch ($(this).data('state')) {
        case 'show':
          $(this).html( $(this).html().replace('Show','Hide') );
          $(this).removeClass('btn-warning').addClass('btn-success');
          $('.showable-password').attr('type','text');
          $(this).data('state','hide');
          break;
        default:
          $(this).html( $(this).html().replace('Hide','Show') );
          $(this).removeClass('btn-success').addClass('btn-warning');
          $('.showable-password').attr('type','password');
          $(this).data('state','show');
      }

      e.preventDefault();
    });
  });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    
    title Friends
    
    = csrf_meta_tags
    
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
  body
    #wrap
      - if current_user
        == render partial: 'layouts/navigation'
      - else
        == render partial: 'layouts/header'
    
      .container
        .page
          == yield
          
    #footer
      .container
        p.text-muted.credit
          => link_to "Privacy Policy", privacy_url
          ' •
          => link_to "Terms of Use", terms_url
          ' • © 2013 Friends

    == render partial: 'layouts/messages'